console.log(+'50', typeof (+'50'))
console.log(Number('100'), typeof Number('100'))
console.log(('' + 1), typeof ('' + 1))
console.log(String(1), typeof String(1))
console.log(Boolean(0), typeof Boolean(0))
console.log(+'001', typeof (+'001'))
console.log((1 + ''), typeof (1 + ''))
console.log(Boolean(1), typeof Boolean(1))
console.log(String(001), typeof String(001))
console.log(Number('Hello World'), typeof Number('Hello World'))
